### ISSUE TITLE
隐藏侧边栏的时候全部子控件打印布局错误❌怎么解决呀 ?

### ISSUE THREAD

**Issue by mafiaIOS** [SongLazy/SLSlideMenu#3]
<NSLayoutConstraint:0x604000097520 H:[walnut_plan.CategoryButton:0x7f9321694100'基础疾病']-(12)-|   (active, names: '|':walnut_plan.CategoryListView:0x7f9321682410 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-12-03 15:06:23.258130+0800 walnut_plan[31720:6397710] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x60400009a770 h=--& v=--& UIView:0x7f931ec137e0.width == 0   (active)>",
    "<NSLayoutConstraint:0x60400008fa00 H:[UILabel:0x7f931ec2fc80'\U4e2a\U4eba\U4fe1\U606f\U586b\U5199\U5f97\U8d8a\U8be6\U7ec6,\U6d4b\U8bd5\U7ed3\U679c\U8d8a\U7cbe\U51c6\Uff01']-(15)-|   (active, names: '|':walnut_plan.CategoryListView:0x7f9321682410 )>",
    "<NSLayoutConstraint:0x60400009f540 H:|-(15)-[UILabel:0x7f931ec2fc80'\U4e2a\U4eba\U4fe1\U606f\U586b\U5199\U5f97\U8d8a\U8be6\U7ec6,\U6d4b\U8bd5\U7ed3\U679c\U8d8a\U7cbe\U51c6\Uff01']   (active, names: '|':walnut_plan.CategoryListView:0x7f9321682410 )>",
    "<SnapKit.LayoutConstraint:0x6040000b6da0@EditorInformationController.swift#266 walnut_plan.CategoryListView:0x7f9321682410.left == UIView:0x7f931ec137e0.left>",
    "<SnapKit.LayoutConstraint:0x6040000b6d40@EditorInformationController.swift#266 walnut_plan.CategoryListView:0x7f9321682410.right == UIView:0x7f931ec137e0.right>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60400008fa00 H:[UILabel:0x7f931ec2fc80'个人信息填写得越详细,测试结果越精准！']-(15)-|   (active, names: '|':walnut_plan.CategoryListView:0x7f9321682410 )>

**Comment by SongLazy** [comment]
额  你是用的神马布局？

**Comment by mafiaIOS** [comment]
> 额 你是用的神马布局？

xib 创建的一个视图, prepare方法添加到侧边栏上,然后snp做的自动布局 . 没有其他操作... dismiss的时候回报错子控件上的约束错误

**Comment by SongLazy** [comment]
dismiss之前先把里面的view移除了可以吗。这个我已经好久没有动过它了，实在不行晚上下班回家我看一下。

**Comment by mafiaIOS** [comment]
> dismiss之前先把里面的view移除了可以吗。这个我已经好久没有动过它了，实在不行晚上下班回家我看一下。

  categoryListView.didSelectCloseButton = {[weak self] in
            self?.categoryListView.removeFromSuperview()
            SLSlideMenu.dismiss()
        }

我是在这里做的remove操作 , 还是不管用

**Comment by mafiaIOS** [comment]
> > dismiss之前先把里面的view移除了可以吗。这个我已经好久没有动过它了，实在不行晚上下班回家我看一下。
> 
> categoryListView.didSelectCloseButton = {[weak self] in
> self?.categoryListView.removeFromSuperview()
> SLSlideMenu.dismiss()
> }
> 
> 我是在这里做的remove操作 , 还是不管用

**Comment by mafiaIOS** [comment]
> dismiss之前先把里面的view移除了可以吗。这个我已经好久没有动过它了，实在不行晚上下班回家我看一下。

 func slideMenu(_ slideMenu: SLSlideMenu!, prepareSubviewsForMenuView menuView: UIView!) {
        menuView.addSubview(categoryListView)
        // 布局
        categoryListView.snp.makeConstraints { (make) in
            make.top.left.right.bottom.equalToSuperview()
        }

我是这样添加到侧边栏上的 , categoryListView 是xib加载的view

**Comment by SongLazy** [comment]
你创建的时候别用自动布局，用frame布局。

**Comment by mafiaIOS** [comment]
> 你创建的时候别用自动布局，用frame布局。

  // 自定义视图的代理方法param slideMenu slideMenuparam menuView 将子控件添加到menuView
    func slideMenu(_ slideMenu: SLSlideMenu!, prepareSubviewsForMenuView menuView: UIView!) {
        menuView.addSubview(categoryListView)
        // 布局
        categoryListView.snp.makeConstraints { (make) in
            make.top.left.right.bottom.equalToSuperview()
        }
你指的是xib 视图view添加到侧边栏上的时候 这个snp吗?

**Comment by SongLazy** [comment]
嗯啊

**Comment by mafiaIOS** [comment]
> 嗯啊

   func slideMenu(_ slideMenu: SLSlideMenu!, prepareSubviewsForMenuView menuView: UIView!) {
       
        categoryListView.frame = menuView.frame
       
        menuView.addSubview(categoryListView)
}

我这样添加的还是报错 xib里面的布局问题

**Comment by SongLazy** [comment]
那你看看xib的约束啥的吧  UILabel 的约束可能有问题

**Comment by mafiaIOS** [comment]
> 那你看看xib的约束啥的吧 UILabel 的约束可能有问题

好的 , Thanks

**Comment by SongLazy** [comment]
不客气-，-

**Comment by mafiaIOS** [comment]
找到问题了: 因为是点击空白处自动隐藏的, removeFromSuperView 这句代码根本没地方执行 , 监听touchupInside 方法能解决问题吗?

**Comment by mafiaIOS** [comment]
好像不行,  只能不让它滑动隐藏了吗?

**Comment by SongLazy** [comment]
实在不行你改下源码吧，我现在手边也没有mac。。   在 shadowViewDidClick 里 的animateWithDuration的completion里面 把self的子控件都删了

**Comment by mafiaIOS** [comment]
> 实在不行你改下源码吧，我现在手边也没有mac。。 在 shadowViewDidClick 里 的animateWithDuration的completion里面 把self的子控件都删了

好的

**Comment by mafiaIOS** [comment]
> > 实在不行你改下源码吧，我现在手边也没有mac。。 在 shadowViewDidClick 里 的animateWithDuration的completion里面 把self的子控件都删了
> 
> 好的



> 实在不行你改下源码吧，我现在手边也没有mac。。 在 shadowViewDidClick 里 的animateWithDuration的completion里面 把self的子控件都删了

```
 [UIView animateWithDuration:animationTime animations:^{
        self.menuView.frame = frame;
        if (self.direction == SLSlideMenuDirectionLeft) {

            [self.menuView.subviews enumerateObjectsUsingBlock:^(__kindof UIView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                CGRect subFrame = obj.frame;
                subFrame.origin.x = [[_startX_arr objectAtIndex:idx] floatValue];
                obj.frame = subFrame;
            }];
        }
        
        if (self.direction == SLSlideMenuDirectionTop) {
            [self.menuView.subviews enumerateObjectsUsingBlock:^(__kindof UIView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                CGRect subFrame = obj.frame;
                subFrame.origin.y = [[_startY_arr objectAtIndex:idx] floatValue];
                obj.frame = subFrame;
            }];
        }
        
        self.shadowView.backgroundColor = [UIColor colorWithRed:10/255.0 green:10/255.0 blue:10/255.0 alpha:0.0];
    } completion:^(BOOL finished) {
        [self removeFromSuperview];
       
        for(int i = 0;i<=[self.shadowView.subviews count];i++){
            [[self.shadowView.subviews objectAtIndex:i] removeFromSuperview];
        }
        
        [self.shadowView removeFromSuperview];
    
        
        
        [[NSNotificationCenter defaultCenter] removeObserver:self name:@"dismissSLSLideMenu" object:nil];
    }];
}
```

**Comment by mafiaIOS** [comment]
> 实在不行你改下源码吧，我现在手边也没有mac。。 在 shadowViewDidClick 里 的animateWithDuration的completion里面 把self的子控件都删了

```
completion:^(BOOL finished) {
        [self removeFromSuperview];
       
        for(int i = 0;i<=[self.shadowView.subviews count];i++){
            [[self.shadowView.subviews objectAtIndex:i] removeFromSuperview];
        }
        
        [self.shadowView removeFromSuperview];
    
```

我在completion 这句代码里面写的  , 好像没效果

**Comment by SongLazy** [comment]
在
`[self removeFromSuperview];` 
之前，
删self的子控件，
先判断一下self有木有子控件，有的话就删了，
不是删self.shadowView的子控件

**Comment by mafiaIOS** [comment]
> 在
> `[self removeFromSuperview];`
> 之前，
> 删self的子控件，
> 先判断一下self有木有子控件，有的话就删了，
> 不是删self.shadowView的子控件

0.0];
    } completion:^(BOOL finished) {
     
        if ([self.subviews count] > 0 ){
            for(int i = 0;i<=[self.subviews count] - 1;i++){
                [[self.subviews objectAtIndex:i] removeFromSuperview];
            }
        }
        [self removeFromSuperview];
        
        [self.shadowView removeFromSuperview];
        
        [[NSNotificationCenter defaultCenter] removeObserver:self name:@"dismissSLSLideMenu" object:nil];
    }];
}

打印没子控件 , 还是报错

**Comment by SongLazy** [comment]
额 这样吧  你这个功能急不急？ 如果不急的话你发个demo给我 我晚上回家看看。songlazy@foxmail.com

**Comment by mafiaIOS** [comment]
> 额 这样吧 你这个功能急不急？ 如果不急的话你发个demo给我 我晚上回家看看。[songlazy@foxmail.com](mailto:songlazy@foxmail.com)

已经在审核中, 但是这个问题一直在 ;  不知道怎么解决 demo没有 就是全码了

**Comment by mafiaIOS** [comment]
手动点击处做了移出处理 , 没打印错误  就是手势这里有问题

**Comment by SongLazy** [comment]
这个导致崩溃没

**Comment by mafiaIOS** [comment]
> 这个导致崩溃没

没崩溃 , 就是打印 布局问题

**Comment by SongLazy** [comment]
嗯 那还好点儿-，-  等着我写个demo模拟一下你这个场景试试。加个qq？

**Comment by mafiaIOS** [comment]
> 嗯 那还好点儿-，- 等着我写个demo模拟一下你这个场景试试。加个qq？

QQ : 1669352442 谢谢

**Comment by SongLazy** [comment]
欧了
